/**
 * Turns a spec written in builder.html into the committed questions file.
 *
 *   node tools/spec-apply.mjs work-test-spec.json
 *   node tools/spec-apply.mjs work-test-spec.json --dry
 *
 * This is the "ship it" step, and it is deliberately a command that produces a diff rather than
 * a button that publishes. The builder has no authentication of any kind, and what it would be
 * publishing is a live hiring assessment, so the gate between "an author is happy with it" and
 * "candidates are sitting it" is a reviewed commit and a deploy.
 *
 * It refuses to write a spec with flow errors. A dangling branch is invisible until a candidate
 * walks into it, on a clock, which is the worst possible moment to discover one.
 *
 * wt-questions.mjs is GENERATED by this script, so a hand edit to it is lost on the next run.
 * Put changes in the spec instead, or run tools/spec-export.mjs first to pull the current file
 * back into a spec and edit that.
 *
 * Anything that has to survive regeneration goes in the spec's `notes` field, which is written
 * into the header of the generated file. That is where provenance belongs: which document the
 * task came from, what was deliberately left ambiguous, why a part is worded oddly. Losing that
 * to a regeneration is how a test slowly stops making sense to the people maintaining it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { validateFlow } from '../functions/_lib/wt-flow.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const TARGET = `${ROOT}functions/_lib/wt-questions.mjs`;

const file = process.argv[2];
const dry = process.argv.includes('--dry');

if (!file || file.startsWith('--')) {
  console.error('Usage: node tools/spec-apply.mjs <spec.json> [--dry]');
  process.exit(1);
}

let spec;
try {
  spec = JSON.parse(readFileSync(file, 'utf8'));
} catch (err) {
  console.error(`Could not read ${file}: ${err.message}`);
  process.exit(1);
}

/* ------------------------------------------------------------------ checks ---------- */

const problems = validateFlow(spec.questions || []);

// The link URLs are the one place an author's text reaches an HTML attribute, so they are
// checked here as well as in the builder. A spec can arrive by any route, including by hand.
for (const [key, brief] of Object.entries(spec.briefs || {})) {
  for (const block of brief.blocks || []) {
    if (block.type === 'link' && !/^https?:\/\/\S+$/i.test(block.url || '')) {
      problems.push({ level: 'error', message: `The link in brief "${key}" is not an http(s) address.` });
    }
  }
}
if (!Array.isArray(spec.sections) || !spec.sections.length) {
  problems.push({ level: 'error', message: 'The spec has no parts (sections).' });
}
if (!Number.isFinite(spec.durationSec) || spec.durationSec <= 0) {
  problems.push({ level: 'error', message: 'durationSec must be a positive number of seconds.' });
}

for (const p of problems) console.log(`  ${p.level === 'error' ? 'error  ' : 'warning'} ${p.message}`);

const errors = problems.filter((p) => p.level === 'error');
if (errors.length) {
  console.error(`\n${file} has ${errors.length} error${errors.length === 1 ? '' : 's'}. Nothing written.`);
  process.exit(1);
}

/* ------------------------------------------------------------------ writing --------- */

const lit = (v) => JSON.stringify(v, null, 2)
  .split('\n')
  .map((line, i) => (i === 0 ? line : `  ${line}`))
  .join('\n');

const planned = spec.sections.reduce((n, s) => n + (Number(s.recommendedMin) || 0), 0);

// Wrapped to a sane width and comment-escaped, so a note can be a paragraph without either
// breaking the comment or turning into one very long line.
const notesBlock = (() => {
  const raw = String(spec.notes || '').replace(/\*\//g, '* /').trim();
  if (!raw) return ' *';
  const lines = [];
  for (const para of raw.split(/\n{2,}/)) {
    if (lines.length) lines.push(' *');
    let line = '';
    for (const word of para.split(/\s+/)) {
      if (line && (line + ' ' + word).length > 92) { lines.push(` * ${line}`); line = word; }
      else line = line ? `${line} ${word}` : word;
    }
    if (line) lines.push(` * ${line}`);
  }
  return ` *\n${lines.join('\n')}\n *`;
})();

const out = `/**
 * The test itself. GENERATED by tools/spec-apply.mjs, so edit the spec and re-run it rather
 * than editing here: the next run overwrites this file. tools/spec-export.mjs turns this file
 * back into a spec if the only copy you have is this one.
 *
 * Written from: ${file}
${notesBlock}
 * These questions live server-side on purpose. The candidate's browser is only ever sent the
 * question it is currently on, plus the brief for the part it belongs to, and an option's
 * branch destination is stripped before it leaves the server, so nobody can read ahead or work
 * out what a choice costs them before making it.
 */

/** Total time for the WHOLE test, in seconds. The parts below recommend ${planned} minutes. */
export const DURATION_SEC = ${spec.durationSec};

/**
 * Seconds of slack allowed after the deadline before an answer is refused. Covers network
 * latency so an answer sent a moment before the buzzer is not lost. Keep small.
 */
export const GRACE_SEC = ${Number.isFinite(spec.graceSec) ? spec.graceSec : 5};

/**
 * Candidates are told they may use AI and a calculator, so paste counts are not evidence of
 * anything and are not presented as such. Time per question is still recorded because it is
 * genuinely informative about prioritization. blockPaste stays false: it would break the
 * "you may use AI" promise.
 */
export const INTEGRITY = { blockPaste: ${(spec.integrity && spec.integrity.blockPaste) === true || spec.blockPaste === true} };

/**
 * How the clock works. 'total' is one countdown for the sitting, 'section' gives each part its
 * own limit and moves the candidate on when one runs out, 'none' is untimed.
 */
export const TIMING = ${lit(spec.timing || { mode: 'total' })};

/**
 * Whether a candidate may look back at earlier answers, and whether they may change them.
 * Both default to false. Turning \`edit\` on changes what the test measures rather than only how
 * it feels, and a revision that changes a branch discards the answers that followed it.
 */
export const NAVIGATION = ${lit(spec.navigation || { back: false, edit: false })};

/**
 * The parts of the instructions page an author writes: task-specific rules, the prose after
 * them, and a contact address. The rules describing what the engine enforces are generated from
 * the settings, so they cannot drift out of step with the test.
 */
export const INTRO = ${lit(spec.intro || {})};

/**
 * The closing screen's author-written half. What was submitted, and whether it can still be
 * changed, is worked out by the engine.
 */
export const OUTRO = ${lit(spec.outro || {})};

/**
 * The parts of the task, in order, with how long each is expected to take. \`recommendedMin\`
 * drives the weighting of the progress bar, so a candidate can see which part is the bulk of
 * the work rather than counting questions and assuming the halfway question is the halfway
 * point. These should sum to roughly DURATION_SEC so the bar and the clock agree.
 */
export const SECTIONS = ${lit(spec.sections)};

/**
 * Reference material that stays on screen for every question in a part. Block types the client
 * knows how to render: 'p' (paragraph), 'quote' (a Slack or email, with a label and optional
 * numbered list), 'link' (a button out to the data).
 */
export const BRIEFS = ${lit(spec.briefs || {})};

/**
 * Question types: 'short', 'long', 'rich', 'choice'. See wt-flow.mjs for how \`next\` and an
 * option's \`next\` decide the route, and note that a question with neither simply falls through
 * to the following one in this array.
 */
export const QUESTIONS = ${lit(spec.questions)};
`;

if (dry) {
  process.stdout.write(out);
  console.error(`\n(dry run, nothing written to ${TARGET})`);
} else {
  writeFileSync(TARGET, out);
  const warnings = problems.length;
  console.log(`\nWrote functions/_lib/wt-questions.mjs: ${spec.questions.length} questions, ${spec.sections.length} parts${warnings ? `, ${warnings} warning${warnings === 1 ? '' : 's'} above` : ''}.`);
  console.log('Now: git diff, run node --test tools/*.test.mjs, then commit and deploy.');
}
